### ISSUE TITLE
Values are not updated

### ISSUE THREAD

**Issue by ZyberSE** [rsnodgrass/hass-sensorpush#1]
In the beginning sensor values were fethed but after an hour or so the issue started occurring.
At time of writing it's happened 24 140 times and I've had your plugin installed for less than 24h.

`Exception in _update_callback when dispatching 'sensorpush_updated': ()
Traceback (most recent call last):
  File "/config/custom_components/sensorpush/__init__.py", line 155, in _update_callback
    sensor_results = samples['sensors']
TypeError: 'NoneType' object is not subscriptable`

I'm running HASS.io 0.98.2

**Comment by rsnodgrass** [comment]
Looking into this.  Did it start working again if you restarted HASS?  I suspect that the SensorCloud authentication token expired and my client is not automatically re-authenticating.

**Comment by rsnodgrass** [comment]
I uploaded a version which uses the latest pysensorpush API to automatically re-authenticate whenever the SensorPush connection expires. I'm running it now, and will confirm if the error has gone away. You should be able to quickly update as well through HACS.

**Comment by rsnodgrass** [comment]
Please confirm this update has resolved the issue.
