### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by thetravellor** [rsnodgrass/hass-sensorpush#11]
I have configured the respository in Home assistant and configured the integration in configuration.yaml, but homeassistant rejects:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:407
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 8:23:21 (2 occurrences)
Last logged: 8:26:05

Component error: sensors - Integration 'sensors' not found. Invalid config for [sensorpush]: string value is None for dictionary value @ data['sensorpush']['password']. Got None. (See /config/configuration.yaml, line 60).

I suspect it doesnt like the "#" in my password?

**Comment by Next9999** [comment]
i had the same king of issue.... ... i change my password removing  "special character"

**Comment by rsnodgrass** [comment]
You have to quote "#", else it is a comment in yaml.
