### ISSUE TITLE
enhancement Alert for the cloud

### ISSUE THREAD

**Issue by Next9999** [rsnodgrass/hass-sensorpush#15]
Hi

is there a way to add the alert that is coming from the cloud that show that the value of the data is outside the limit

it the attachment we see that the outside temperature is outside the limit... a Red Dot is show

![Web capture_16-1-2021_233250_dashboard sensorpush com](https://user-images.githubusercontent.com/54117519/104831062-2d45a180-5853-11eb-8ee7-07d07e37a619.jpeg)

**Comment by rsnodgrass** [comment]
I'm not sure if the limits are returned in the cloud API, but if they are it is a good idea to add them to the sensors as attributes.

**Comment by rsnodgrass** [comment]
Could you send me the "Instantiating SensorPush sensors" log line from your logs?  I want to verify what is there for any new sensors.

**Comment by rsnodgrass** [comment]
Any min/max limit values set in the app are now attributes on the sensor values that appear in Home Assistant.  Any visualizations that something is out of the limits can be done through "template sensors" and Locelave.
