### ISSUE TITLE
Alert- Min Max only in Fahrenheit

### ISSUE THREAD

**Issue by Next9999** [rsnodgrass/hass-sensorpush#17]
Hello

I notice that the Min-Max Alert are only in Fahrenheit

tks for adding the new attributes,

![image](https://user-images.githubusercontent.com/54117519/105579228-3521ac00-5d53-11eb-8c46-c3b6ca173743.png)

**Comment by rsnodgrass** [comment]
The Sensorpush API does not return units, it must always return in Fahrenheit.  I have made a change in 'master' that converts locally to Celsius when the metric unit system is configured.  Can you install master and let me know if this solves your issue?  If so, I will release this.

**Comment by Next9999** [comment]
..not sure how to do that?

do i renamed the __init__.py has"|old__init__.py" then copy and paste the new code as __init__.py?
