### ISSUE TITLE
Definitely does not work without the G1 gateway on iOS

### ISSUE THREAD

**Issue by ChrisBaker97** [rsnodgrass/hass-sensorpush#9]
I have three sensors connected through a G1 gateway and two others at two additional locations that only update through my iOS device. Although the SensorPush site shows the name of these two sensors, and although there is plenty of data in my phone app from them, there is no data on the SensorPush site from these two sensors, and thus nothing for Home Assistant to fetch. (The sensors at the location with the G1 gateway work great.) Just wanted to let you (and anyone else) know, since it was kind of ambiguous in the [README](https://github.com/rsnodgrass/hass-sensorpush/blob/master/README.md) and the [forum post](https://community.home-assistant.io/t/sensorpush-humidity-and-temperature-sensors/105711) as to whether bluetooth updates would work. At least as far as I can tell, they don't.

**Comment by rsnodgrass** [comment]
Interesting, thanks for letting me know.  I have two G1 gateways, so never have used one directly with an iOS device.

**Comment by Next9999** [comment]
> I have three sensors connected through a G1 gateway and two others at two additional locations that only update through my iOS device. Although the SensorPush site shows the name of these two sensors, and although there is plenty of data in my phone app from them, there is no data on the SensorPush site from these two sensors, and thus nothing for Home Assistant to fetch. (The sensors at the location with the G1 gateway work great.) Just wanted to let you (and anyone else) know, since it was kind of ambiguous in the [README](https://github.com/rsnodgrass/hass-sensorpush/blob/master/README.md) and the [forum post](https://community.home-assistant.io/t/sensorpush-humidity-and-temperature-sensors/105711) as to whether Bluetooth updates would work. At least as far as I can tell, they don't.

**Comment by Next9999** [comment]
@ChrisBaker97  Are the new sensors? because if they are... According to "SensorPush" the cloud data will be available for those  only late January 2020

i got those new one and the data is only available on the phone not on the cloud
-HT.w Water-Resistant Temperature / Humidity
HTP.xw Extreme Accuracy Water-Resistant

**Comment by rsnodgrass** [comment]
@ChrisBaker97 so the SensorPush app must not publish the values to the cloud for app-only configurations.  If the data is not in the cloud, there is no way for HA to access it.
